# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory
WORKDIR /usr/src/app

# Install iperf3
RUN apt-get update && apt-get install -y iperf3

# Copy the client script into the container
COPY client.py .

# The client container does not need to start automatically
CMD ["python3", "client.py"]
