# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory
WORKDIR /usr/src/app

# Install iperf3
RUN apt-get update && apt-get install -y iperf3

# Copy the server script into the container
COPY server.py .

# Run server.py when the container launches
CMD ["python3", "server.py"]
