# Use Ubuntu as the base image
FROM ubuntu:latest

# Install iperf3
RUN apt-get update && apt-get install -y iperf3

# Expose the port iperf3 uses
EXPOSE 5201

# Command to run iperf3 in server mode
CMD ["iperf3", "-s"]
